controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_login:
    path: /login
    controller: App\Controller\LoginController::login
profile:
    path: /profile/{id}
    controller: App\Controller\ProfileController::profile


